###
# Application Specific Configuration
###
stockmgr:
  rest:
    date_pattern: yyyyMMdd
    default_fromdate: 20180101
    timezone: HKT
    allowed_cors: http://localhost:3000
  ta:
    default_timeframe: 250